name: Build & Release Go Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Go binary
        run: go build -o codeowners-generator ./cmd/codeowners-generator

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeowners-generator
          path: codeowners-generator

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: codeowners-generator

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: "Automated Release"
          tag_name: "latest"
          files: codeowners-generator
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
